#TASK: ('hop', 'turn_round', 'group', 'entry')
TASK: ('hop', 'turn_round', 'entry')

# hop detect
HOP:
  CLASSES: ('hat', 'sunglasses', 'mask')
  DATA_PATH: ('PostProcess/data/atm_mini2-atm_hop/result.json',)
# turn round detect
TROUND:
  TIMES: 3
  TROUND_SENSE: 0.5
  FRONT_SENSE: (0.8, 1.2)
  DATA_PATH: ('PostProcess/data/atm_mini2-atm_3dkpts/result.json',)

# group person detect
GROUP:
  MAX_NUM: 2
  DATA_PATH: ('PostProcess/data/atm_mini2-atm_face/result.json',)

# multi entry detect
ENTRY:
  FREQUENCY: 3
  DATA_PATH: ('PostProcess/data/atm_mini2-atm_3dkpts/result.json', 'PostProcess/data/atm_mini2-atm_reco/result.json')
